### ISSUE TITLE
How to see if connected?

### ISSUE THREAD

**Issue by RonXTCdaBass** [Stukeley/ArduinoTwitchBot#2]
Hello and thanks for this nice Idea!
i have installed the NET. and the 64bit version runs.  [https://github.com/Stukeley/ArduinoTwitchBot/releases/download/v1.1/x64-framework-dependent.zip](url)
the test signal works with the arduino, but where can i see if the bot is really connected to the Chat?
and another thing - i use win7 and cannot see the "Emote" feature...

**Comment by Stukeley** [comment]
The "Emote" feature is currently being reworked, to allow for better scalability and more intuitive performance - I will let you know in a few days when it's finished, as I cannot really troubleshoot the issues with the previous version now.

> where can I see if the bot is really connected to the Chat?

Right now, if you press Connect and no Message Box shows up, it means the bot has connected to the chat - there should also be some text displayed on the screen with the bot's status (eg. "Listening to: Follows"), right above the Connect/Disconnect button.

**Comment by RonXTCdaBass** [comment]
Hello and thanks for the fast answer!!

i see no popup - message box 
but also no "bot's status (eg. "Listening to: Follows"), right above the Connect/Disconnect button."

[screenshot1](https://ronxtcdabass.lima-city.de/pics/Arduino%20TwitchBot.png) 
[screenshot2](https://ronxtcdabass.lima-city.de/pics/Arduino%20TwitchBot_02.png)
i´ve testet the FOLLOW with my bot account, but nothing... my LED´s only working while pressing the TEST Button in the app. (all signals)

**Comment by Stukeley** [comment]
I have made a new release [here](https://github.com/Stukeley/ArduinoTwitchBot/releases/tag/v1.2), which changes some functionality but also bumps the .NET version (and other dependencies).

Could you test it and see if that works? If not, we'll try to troubleshoot from there.

If you go for the Framework-Dependent version, you will need to install .NET 6 runtimes from [here](https://dotnet.microsoft.com/en-us/download/dotnet/6.0), as described in the README. However, you can also try the Self-Contained version - you shouldn't have to install anything else.

**Comment by RonXTCdaBass** [comment]
GREAT!!! 
Big Thanks!!!
this seems working. now i see after the connect, the Msg. "Listening to..." 
the connect button changes to "disconnect" and it reacts to the chat message alert. :) :) :) 

also i use a modified arduino file for 7 LED´s 

now it will be time for a lifestream to test the functions ;)

**Comment by Stukeley** [comment]
Great, thank you!

I will close this issue for now. If something else is wrong, or if you have any other functionality suggestions, feel free to make a new one or contact me otherwise.

Have a great stream!
